### ISSUE TITLE
Possible CDDL Error In Network Base

### ISSUE THREAD

**Issue by mskymoore** [many-protocol/specification#31]
I'm new to cddl, but it looks like based on this comment and the [specification RFC 8610](https://www.rfc-editor.org/rfc/rfc8610#section-3.2) there should be a "*" occurence modifier on line 40.

https://github.com/many-protocol/specification/blob/8673f88d62e673f169c7d3352f1e90b29a5f7c06/attributes/network/cddl/0_base.cddl#L39-L41

> [3.2](https://www.rfc-editor.org/rfc/rfc8610#section-3.2).  Occurrence

>  An optional _occurrence_ indicator can be given in front of a group
>  entry.  It is either (1) one of the characters "?" (optional), "\*"
>  (zero or more), or "+" (one or more) or (2) of the form n\*m, where n
>   and m are optional unsigned integers and n is the lower limit
>   (default 0) and m is the upper limit (default no limit) of
>   occurrences.
>
>   If no occurrence indicator is specified, the group entry is to occur
>   exactly once (as if 1*1 were specified).  A group entry with an
>   occurrence indicator matches sequences of name/value pairs that are
>   composed by concatenating a number of sequences that the basic group
>   entry matches, where the number needs to be allowed by the occurrence
>   indicator.
---
> [3.5.1](https://www.rfc-editor.org/rfc/rfc8610#section-3.5.1).  Structs
>  ...
>   If the addition of more entries not specified by the current
>   specification is desired, one can add this possibility explicitly:
>
>                          PersonalData = {
>                            ? displayName: tstr,
>                            NameComponents,
>                            ? age: uint,
>                            * tstr => any
>                          }
>
>                          NameComponents = (
>                            ? firstName: tstr,
>                            ? familyName: tstr,
>                          )
>
>            Figure 7: Personal Data: Example for Extensibility

In the present form it would require one additional field with a text string as a key, and not allow many.

**Comment by hansl** [comment]
That is correct. Thanks for catching this.
