### ISSUE TITLE
Echo not present in network base cddl

### ISSUE THREAD

**Issue by mskymoore** [many-protocol/specification#32]
Still learning here, but noticed that the echo function is mentioned in the asciidoc, but not present in the cddl.  I think it should look like this.  Not sure how else to describe the signed data envelope besides a struct.  Looking for feedback.  Thank you @hansl .

```
; tag::echo[]
echo@param = bstr
echo@return = echo

echo = {
    ; Argument bytes sent back
    echo: echo@param,
    ; Signature
    signature: bstr,
}
; end::echo[]
```

**Comment by hansl** [comment]
We removed `echo` at some point. Might have forgotten to remove the CDDL. The reasoning is that `echo` is not a very useful feature and if you want to test a server `status` is probably enough.
